environment:
  LINUX_IMAGE: &linux_image Ubuntu2204
  MACOS_IMAGE: &macos_image macos-monterey
  WINDOWS_IMAGE: &windows_image Visual Studio 2022
  LIBZEN_VERSION: 0.4.41
  MEDIAINFO_VERSION: 23.10
  UBUNTU_VERSION: 22.04
  QA_PYTHON_VERSION: 3.12
  DEPLOY_TOXENV: py312
  PYPY_URL: https://downloads.python.org/pypy/pypy3.10-v7.3.13-linux64.tar.bz2
  # Work around https://github.com/tox-dev/tox/issues/1550
  PYTHONIOENCODING: utf-8
  TOX_PARALLEL_NO_SPINNER: 1
  TWINE_USERNAME: "__token__"
  TWINE_PASSWORD:
    secure: Jp2QpmAii1mmAXmotdXmPx5q679oMcRolziuu9m2pawkvOnRJtWMsI4uWiTiSbiw+HMbyyWwVpy+FiaPsHZxtM863PNNJidW1WDam4kn8EM+rznjgZfO9NSCcwZJU5jcTYCwuXo3+FnVNK5rvQ8QJ+Zu6WzH1Ysb+uJSz8e6xt7d7hoZbb9VH5bJC7tYrw+bH+TfA9juVpIYfCavozLLTDLqTcvPfJ+LXMPbiZO+oOztNsLRsviH2QAPXaLspXvCr6qUVH3A84KCdfSXCOZG0g/eYUZ6ilMLESe7DrYZrRc=
  matrix:
    - TOXENV: docs,black,flake8,isort,mypy,pylint
      APPVEYOR_BUILD_WORKER_IMAGE: *linux_image
    - TOXENV: pypy3
      APPVEYOR_BUILD_WORKER_IMAGE: *linux_image
    - TOXENV: py39
      APPVEYOR_BUILD_WORKER_IMAGE: *linux_image
    - TOXENV: py310
      APPVEYOR_BUILD_WORKER_IMAGE: *linux_image
    - TOXENV: py311
      APPVEYOR_BUILD_WORKER_IMAGE: *linux_image
    - TOXENV: py312
      APPVEYOR_BUILD_WORKER_IMAGE: *linux_image
    - TOXENV: py313
      APPVEYOR_BUILD_WORKER_IMAGE: *linux_image
    - TOXENV: py39
      APPVEYOR_BUILD_WORKER_IMAGE: *macos_image
    - TOXENV: py310
      APPVEYOR_BUILD_WORKER_IMAGE: *macos_image
    - TOXENV: py311
      APPVEYOR_BUILD_WORKER_IMAGE: *macos_image
    - TOXENV: py312
      APPVEYOR_BUILD_WORKER_IMAGE: *macos_image
    - TOXENV: py39
      PYTHON: "C:/Python39"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
    - TOXENV: py39
      PYTHON: "C:/Python39-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
    - TOXENV: py310
      PYTHON: "C:/Python310"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
    - TOXENV: py310
      PYTHON: "C:/Python310-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
    - TOXENV: py311
      PYTHON: "C:/Python311"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
    - TOXENV: py311
      PYTHON: "C:/Python311-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
    - TOXENV: py312
      PYTHON: "C:/Python312"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
    - TOXENV: py312
      PYTHON: "C:/Python312-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
    - TOXENV: py313
      PYTHON: "C:/Python313"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
    - TOXENV: py313
      PYTHON: "C:/Python313-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
for:
-
  matrix:
    only:
    - APPVEYOR_BUILD_WORKER_IMAGE: *windows_image
  install:
    - "SET PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%"
    - "python --version"
    - "IF %PYTHON:~-4% == -x64 (SET ARCH=x64) ELSE (SET ARCH=i386)"
    - "IF %PYTHON:~-4% == -x64 (SET PLATFORM_WHEEL=win_amd64) ELSE (SET PLATFORM_WHEEL=win32)"
    - ps: "Start-FileDownload https://mediaarea.net/download/binary/mediainfo/${Env:MEDIAINFO_VERSION}/MediaInfo_CLI_${Env:MEDIAINFO_VERSION}_Windows_${Env:ARCH}.zip"
    - ps: "unzip -o MediaInfo_CLI_${Env:MEDIAINFO_VERSION}_Windows_${Env:ARCH}.zip LIBCURL.DLL"
    - ps: "Start-FileDownload https://mediaarea.net/download/binary/libmediainfo0/${Env:MEDIAINFO_VERSION}/MediaInfo_DLL_${Env:MEDIAINFO_VERSION}_Windows_${Env:ARCH}_WithoutInstaller.7z"
    - ps: "7z -y x MediaInfo_DLL_${Env:MEDIAINFO_VERSION}_Windows_${Env:ARCH}_WithoutInstaller.7z MediaInfo.dll Developers/License.html"
    # Required for tests to pass with tox, Windows looks for DLLs in PATH
    - ps: "Copy-Item -Path MediaInfo.dll -Destination ${Env:PYTHON}"
    - "move MediaInfo.dll pymediainfo"
    - "move Developers\\License.html docs"
    - "pip install tox"
  build: off
  test_script:
    - "tox"
  deploy_script:
    - ps: |
        If (($env:APPVEYOR_REPO_TAG -eq "true") -and ($env:TOXENV -eq $env:DEPLOY_TOXENV)) {
          pip install twine wheel pdm
          pdm build --no-sdist
          wheel tags --remove --platform-tag=${Env:PLATFORM_WHEEL} dist/*-py3-none-any.whl
          Invoke-Expression "twine upload --skip-existing dist/*.whl"
        }
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: *macos_image
  install: |
    set -eo pipefail
    PYTHON_VERSION="$(sed -E 's/^py(3)(.*)$/\1.\2/' <<< "$TOXENV")"
    source "${HOME}/venv${PYTHON_VERSION}/bin/activate"
    pip install tox
    curl https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/MediaInfo_DLL_${MEDIAINFO_VERSION}_Mac_x86_64+arm64.tar.bz2 \
      | tar xj MediaInfoLib/libmediainfo.0.dylib MediaInfoLib/License.html
    # Required for tests to pass with tox
    cp MediaInfoLib/libmediainfo.0.dylib /usr/local/lib/
  build: off
  test_script:
    - "tox"
  deploy_script: |
    set -eo pipefail
    if [[ $APPVEYOR_REPO_TAG == "true" && $TOXENV == $DEPLOY_TOXENV ]]; then
      mv MediaInfoLib/libmediainfo.0.dylib pymediainfo
      mv MediaInfoLib/License.html docs
      pip install twine wheel pdm
      pdm build --no-sdist
      wheel tags --remove --platform-tag=macosx-10.10-x86_64-macosx-11-universal2 dist/*-py3-none-any.whl
      twine upload --skip-existing dist/*.whl
    fi
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: *linux_image
  install: |
    set -eo pipefail
    if [[ $TOXENV =~ doc.* ]]; then
      source "${HOME}/venv${QA_PYTHON_VERSION}/bin/activate"
      pip install tox
    else
      if [[ $TOXENV == pypy3 ]]; then
        pushd /tmp
        curl -sS "$PYPY_URL" | tar xj
        PATH="$(pwd)/$(basename "$PYPY_URL" | sed -E 's/\.tar\.[^.]+$//')/bin/:$PATH"
        python -m ensurepip
        popd
      else
        PYTHON_VERSION="$(sed -E 's/^py(3)(.*)$/\1.\2/' <<< "$TOXENV")"
        source "${HOME}/venv${PYTHON_VERSION}/bin/activate"
      fi
      # "python -m pip" will work with the unpacked PyPy too, "pip" won't
      python -m pip install tox
      pushd /tmp
      libzen_deb=libzen0v5_${LIBZEN_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
      mediainfo_deb=libmediainfo0v5_${MEDIAINFO_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
      curl -O "https://mediaarea.net/download/binary/libzen0/${LIBZEN_VERSION}/${libzen_deb}"
      curl -O "https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/${mediainfo_deb}"
      sudo apt-get -y install libmms0
      sudo dpkg -i "${libzen_deb}" "${mediainfo_deb}"
      popd
    fi
    curl -O https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/MediaInfo_DLL_${MEDIAINFO_VERSION}_Lambda_x86_64.zip
    unzip MediaInfo_DLL_${MEDIAINFO_VERSION}_Lambda_x86_64.zip -d x86_64
    curl -O https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/MediaInfo_DLL_${MEDIAINFO_VERSION}_Lambda_arm64.zip
    unzip MediaInfo_DLL_*_arm64.zip -d arm64
  build: off
  test_script: |
    if [[ $TOXENV =~ doc.* ]]; then
      tox -p
    else
      # We want to see the progression of the tests so we can't run
      # tox environments in parallel
      tox
    fi
  deploy_script: |
    set -eo pipefail
    if [[ $APPVEYOR_REPO_TAG == "true" && $TOXENV == $DEPLOY_TOXENV ]]; then
      pip install twine wheel pdm
      # source distribution
      pdm build --no-wheel

      # wheels
      mv x86_64/LICENSE docs
      # wheel x86_64
      mv x86_64/lib/libmediainfo.so.0.0.0 pymediainfo/libmediainfo.so.0
      pdm build --no-sdist
      wheel tags --remove --platform-tag=manylinux_2_34-x86_64 dist/*-py3-none-any.whl
      # wheel arm64
      mv -f arm64/lib/libmediainfo.so.0.0.0 pymediainfo/libmediainfo.so.0
      pdm build --no-sdist
      wheel tags --remove --platform-tag=manylinux_2_34-arm64 dist/*-py3-none-any.whl

      # upload
      twine upload --skip-existing dist/*.gz dist/*.whl
    fi
